pub const NUMBER_OF_MEASUREMENTS: usize = 50;

pub const NUMBER_OF_POINTS_PER_MEASUREMENT: usize = 8;

pub const NUMBER_OF_POINTS_PER_SCAN: usize =
    NUMBER_OF_POINTS_PER_MEASUREMENT * NUMBER_OF_MEASUREMENTS;

pub const PAYLOAD_SIZE_IN_BYTES: usize = 36;
pub const INDEX_MULTIPLIER: f32 = 400.0 / 360.0;
